-- MySQL Script generated by MySQL Workbench
-- Tue Oct 13 22:16:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tst` DEFAULT CHARACTER SET utf8 ;
USE `tst` ;

-- -----------------------------------------------------
-- Table `tst`.`Servidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tst`.`Servidor` (
  `id_serv` INT NOT NULL COMMENT 'Siape do Servidor',
  `nome_serv` VARCHAR(100) NOT NULL,
  `email_serv` VARCHAR(100) NOT NULL,
  `ramal_serv` INT NOT NULL,
  `permissao_serv` VARCHAR(14) NOT NULL,
  `contato_Pessoal_serv` VARCHAR(16) NOT NULL,
  `login_serv` VARCHAR(20) NOT NULL,
  `senha_serv` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_serv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tst`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tst`.`Cliente` (
  `id_cli` INT NOT NULL AUTO_INCREMENT,
  `nome_cli` VARCHAR(45) NOT NULL,
  `documento_cli` VARCHAR(15) NOT NULL,
  `contato_Alter_serv` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tst`.`Ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tst`.`Ambiente` (
  `id_ambi` INT NOT NULL AUTO_INCREMENT,
  `bloco_ambi` CHAR(2) NOT NULL,
  `salaNum_ambi` CHAR(4) NOT NULL,
  `tipoSala_ambi` VARCHAR(20) NOT NULL COMMENT '1 = Sala Teórica',
  PRIMARY KEY (`id_ambi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tst`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tst`.`Reserva` (
  `id_res` INT NOT NULL AUTO_INCREMENT,
  `contribuicao_res` TINYINT(1) NOT NULL COMMENT 'True/False',
  `dataInicio_res` DATE NOT NULL COMMENT 'DD/MM/AAAA',
  `periodoReservado_res` INT NOT NULL COMMENT 'Os horários são de, M1 até M6, T1 até T6 e N1 até N5\nPara todos horarios = X1\n11 = M1\n12 = M2\n13 = M3\n14 = M4\n15 = M5 \n16 = M6\n21 = T1',
  `observacao_res` VARCHAR(100) NOT NULL,
  `servidor_res` INT NOT NULL,
  `cliente_res` INT NOT NULL,
  `ambiente_res` INT NOT NULL COMMENT 'Descrição dos motivos/ objetivos da reserva',
  PRIMARY KEY (`id_res`),
  INDEX `fk_Reserva_Servidor_idx` (`servidor_res` ASC) VISIBLE,
  INDEX `fk_Reserva_Cliente_idx` (`cliente_res` ASC) VISIBLE,
  INDEX `fk_Reserva_Ambiente_idx` (`ambiente_res` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Servidor`
    FOREIGN KEY (`servidor_res`)
    REFERENCES `tst`.`Servidor` (`id_serv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Cliente`
    FOREIGN KEY (`cliente_res`)
    REFERENCES `tst`.`Cliente` (`id_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Ambiente`
    FOREIGN KEY (`ambiente_res`)
    REFERENCES `tst`.`Ambiente` (`id_ambi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
