/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Filmes;

/**
 *
 * @author pedropereira
 */
public class ViewFilmes extends javax.swing.JFrame {
    controller.ControllerFilmes control = new controller.ControllerFilmes();
    
    private void OpemCadCli(){
        jLabel_tituloAntigo.setVisible(false);
        jLabel_studioAntigo.setVisible(false);
        jButton_encerrar.setText("Encerrar Busca");
        jButton_confirma.setVisible(false);
        jButton_encerrar.setVisible(false);
        control = new controller.ControllerFilmes();
        control.setArquivo("filmes");
        if(control.ler()==true){
            jTextArea_arquivoSalvo.setText(control.getTexto());
        }
    }
    
    private void ClearFields(){
        jLabel_tituloAntigo.setText("");
        jLabel_studioAntigo.setText("");
        jTextField_titulo.setText("");
        jTextField_genero.setText("");
        jTextField_duracao.setText("");
        jComboBox_classificacao.setSelectedIndex(0);
        jTextField_diretor.setText("");
        jCheckBox_filmeAlugado.setSelected(false);
        OpemCadCli();
    }
    
    
    
    /**
     * Creates new form Filmes
     */
    public ViewFilmes() {
        initComponents();
        jTextField_duracao.setDocument(new utils.SoNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jLabel_duracao = new javax.swing.JLabel();
        jLabel_classificacao = new javax.swing.JLabel();
        jLabel_diretor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_arquivoSalvo = new javax.swing.JTextArea();
        jTextField_titulo = new javax.swing.JTextField();
        jTextField_genero = new javax.swing.JTextField();
        jTextField_duracao = new javax.swing.JTextField();
        jComboBox_classificacao = new javax.swing.JComboBox<>();
        jTextField_diretor = new javax.swing.JTextField();
        jCheckBox_filmeAlugado = new javax.swing.JCheckBox();
        jButton_confirma = new javax.swing.JButton();
        jButton_encerrar = new javax.swing.JButton();
        jLabel_tituloAntigo = new javax.swing.JLabel();
        jLabel_studioAntigo = new javax.swing.JLabel();
        jMenuBar_arquivo = new javax.swing.JMenuBar();
        jMenu_arquivos = new javax.swing.JMenu();
        jMenu_buscar = new javax.swing.JMenu();
        jMenuItem_titulo = new javax.swing.JMenuItem();
        jMenuItem_genero = new javax.swing.JMenuItem();
        jMenuItem_duracao = new javax.swing.JMenuItem();
        jMenuItem_classifica = new javax.swing.JMenuItem();
        jMenuItem_studio = new javax.swing.JMenuItem();
        jMenuItem_alugado = new javax.swing.JMenuItem();
        jMenuItem_salvar = new javax.swing.JMenuItem();
        jMenuItem_editar = new javax.swing.JMenuItem();
        jMenuItem_excluir = new javax.swing.JMenuItem();
        jMenuItem_fechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento Filmes");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel_titulo.setText("TÍTULO");

        jLabel_genero.setText("GÊNERO");

        jLabel_duracao.setText("DURAÇÃO");

        jLabel_classificacao.setText("CLASSIFICAÇÃO");

        jLabel_diretor.setText("STUDIO");

        jTextArea_arquivoSalvo.setColumns(20);
        jTextArea_arquivoSalvo.setRows(5);
        jScrollPane1.setViewportView(jTextArea_arquivoSalvo);

        jTextField_duracao.setToolTipText("");
        jTextField_duracao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_duracaoFocusLost(evt);
            }
        });
        jTextField_duracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_duracaoActionPerformed(evt);
            }
        });
        jTextField_duracao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_duracaoKeyTyped(evt);
            }
        });

        jComboBox_classificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "10", "12", "14", "16", "18" }));
        jComboBox_classificacao.setMaximumSize(new java.awt.Dimension(216, 216));
        jComboBox_classificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_classificacaoActionPerformed(evt);
            }
        });

        jCheckBox_filmeAlugado.setText("Filme Alugado");

        jButton_confirma.setText("Confirmar Edição");
        jButton_confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmaActionPerformed(evt);
            }
        });

        jButton_encerrar.setText("Encerrar Busca");
        jButton_encerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_encerrarActionPerformed(evt);
            }
        });

        jMenu_arquivos.setText("Arquivos");

        jMenu_buscar.setText("Buscar");

        jMenuItem_titulo.setText("Por Título");
        jMenuItem_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tituloActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem_titulo);

        jMenuItem_genero.setText("Por Gênero");
        jMenuItem_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_generoActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem_genero);

        jMenuItem_duracao.setText("Por Duração");
        jMenuItem_duracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_duracaoActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem_duracao);

        jMenuItem_classifica.setText("Por  Classificação");
        jMenuItem_classifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_classificaActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem_classifica);

        jMenuItem_studio.setText("Por Studio");
        jMenuItem_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_studioActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem_studio);

        jMenuItem_alugado.setText("Por Alugado");
        jMenuItem_alugado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_alugadoActionPerformed(evt);
            }
        });
        jMenu_buscar.add(jMenuItem_alugado);

        jMenu_arquivos.add(jMenu_buscar);

        jMenuItem_salvar.setText("Salvar");
        jMenuItem_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_salvarActionPerformed(evt);
            }
        });
        jMenu_arquivos.add(jMenuItem_salvar);

        jMenuItem_editar.setText("Editar");
        jMenuItem_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_editarActionPerformed(evt);
            }
        });
        jMenu_arquivos.add(jMenuItem_editar);

        jMenuItem_excluir.setText("Excluir");
        jMenuItem_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_excluirActionPerformed(evt);
            }
        });
        jMenu_arquivos.add(jMenuItem_excluir);

        jMenuItem_fechar.setText("Fechar");
        jMenuItem_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_fecharActionPerformed(evt);
            }
        });
        jMenu_arquivos.add(jMenuItem_fechar);

        jMenuBar_arquivo.add(jMenu_arquivos);

        setJMenuBar(jMenuBar_arquivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel_classificacao)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel_diretor)
                        .addGap(286, 286, 286)
                        .addComponent(jLabel_tituloAntigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_studioAntigo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel_titulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                                        .addComponent(jLabel_genero)
                                        .addGap(100, 100, 100))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField_titulo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBox_classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_genero)
                                            .addComponent(jTextField_diretor, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_filmeAlugado, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel_duracao)))))
                        .addGap(259, 259, 259))))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton_confirma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_encerrar)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_titulo)
                    .addComponent(jLabel_genero)
                    .addComponent(jLabel_duracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_duracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_classificacao)
                    .addComponent(jLabel_diretor)
                    .addComponent(jLabel_tituloAntigo)
                    .addComponent(jLabel_studioAntigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox_filmeAlugado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_diretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_encerrar)
                    .addComponent(jButton_confirma))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(727, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_classificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_classificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_classificacaoActionPerformed

    private void jMenuItem_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_fecharActionPerformed
        ViewLocadora loc = new ViewLocadora();
        loc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_fecharActionPerformed

    private void jMenuItem_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_salvarActionPerformed
        boolean op = false;
        if(!jTextField_titulo.getText().equals("")&&!jTextField_genero.getText().equals("")&&!jTextField_duracao.getText().equals("")&&!jTextField_diretor.getText().equals("")){
            if(jCheckBox_filmeAlugado.isSelected()){
                op=true;
            }else{
                op=false;
            }
            control.setFilme(jTextField_titulo.getText(),jTextField_genero.getText(),Integer.parseInt(jTextField_duracao.getText()),jComboBox_classificacao.getSelectedItem().toString(),jTextField_diretor.getText(),op);
            if(control.getTexto()!=null){
                if(control.getFilmText(jTextField_titulo.getText(),jTextField_diretor.getText())==null){
                    if(control.escrever(true)){
                        jTextArea_arquivoSalvo.setText(control.getTexto());
                        JOptionPane.showMessageDialog(this, "Arquivo escrito com sucesso","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                        ClearFields();
                    }else{
                        JOptionPane.showMessageDialog(this, "Escrita errada","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "FILME já Cadastrado","ERROR", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                if(control.escrever(true)){
                    jTextArea_arquivoSalvo.setText(control.getTexto());
                    JOptionPane.showMessageDialog(this, "Arquivo escrito com sucesso","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                    ClearFields();
                }else{
                    JOptionPane.showMessageDialog(this, "Escrita errada","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Todos Campos devem ser preenchidos","ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem_salvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        OpemCadCli();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_editarActionPerformed
        jButton_confirma.setVisible(true);
        String titulo = JOptionPane.showInputDialog(this, "Informe o TÍTULO do Filme","buscando Filmes", JOptionPane.INFORMATION_MESSAGE);
        String studio = JOptionPane.showInputDialog(this, "Informe o STUDIO que Lançou","buscando Filmes", JOptionPane.INFORMATION_MESSAGE);
        Filmes film = control.getFilmText(titulo, studio);
        if(film == null){
            JOptionPane.showMessageDialog(this, "FILME informado não encontrado!!", "ERRO DE BUSCA", JOptionPane.WARNING_MESSAGE);
            ClearFields();
        }else{
            jTextField_titulo.setText(film.getTitulo());
            jLabel_tituloAntigo.setText(film.getTitulo());
            jTextField_genero.setText(film.getGenero());
            jTextField_duracao.setText(film.getDuracao().toString());
            jComboBox_classificacao.setSelectedItem(film.getClassificacao());
            jTextField_diretor.setText(film.getStudio());
            jLabel_studioAntigo.setText(film.getStudio());
            if(film.getAlugado()==true){
                jCheckBox_filmeAlugado.setSelected(true);
            }else
                jCheckBox_filmeAlugado.setSelected(false);
            jButton_encerrar.setVisible(true);
            jButton_encerrar.setText("Cancelar Edição");
            jButton_confirma.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem_editarActionPerformed

    private void jButton_encerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_encerrarActionPerformed
        ClearFields();
    }//GEN-LAST:event_jButton_encerrarActionPerformed

    private void jButton_confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmaActionPerformed
        String op = "";
        if(jCheckBox_filmeAlugado.isSelected()){
            op="true";
        }else{
            op="false";
        }
        Filmes film = control.getFilmText(jTextField_titulo.getText(), jTextField_diretor.getText());
        if(film == null||(jLabel_tituloAntigo.getText().equals(jTextField_titulo.getText())&&jLabel_studioAntigo.getText().equals(jTextField_diretor.getText()))){
            control.editFilme(jLabel_tituloAntigo.getText(),jLabel_studioAntigo.getText(),jTextField_titulo.getText(), jTextField_genero.getText(), jTextField_duracao.getText(), jComboBox_classificacao.getSelectedItem().toString(), jTextField_diretor.getText(), op);
            ClearFields();
        }else{
            JOptionPane.showMessageDialog(this, "FILME já cadastrado!!", "ERRO DE BUSCA", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton_confirmaActionPerformed

    private void jMenuItem_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_excluirActionPerformed
        String titulo = JOptionPane.showInputDialog(this, "Informe o TÍTULO do Filme","buscando Filmes", JOptionPane.INFORMATION_MESSAGE);
        String studio = JOptionPane.showInputDialog(this, "Informe o STUDIO que Lançou","buscando Filmes", JOptionPane.INFORMATION_MESSAGE);
        Filmes film = control.getFilmText(titulo, studio);
        if(film == null){
            JOptionPane.showMessageDialog(this, "FILME informado não encontrado", "ERRO DE BUSCA", JOptionPane.WARNING_MESSAGE);
        }else{
            if(JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o FILME: "+film.getTitulo()+"\nProduzido por: "+film.getStudio(),"EXCLUIR FILME",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                control.excluiFilme(film.getTitulo(),film.getStudio());
                ClearFields();
                JOptionPane.showMessageDialog(this, "Filme Excluido com sucesso","AVISO",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Ação cancelada","AVISO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem_excluirActionPerformed

    private void jMenuItem_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tituloActionPerformed
        String titulo = JOptionPane.showInputDialog(this, "Informe o TITULO do filme","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        control.buscaFilme(titulo, "titulo");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_tituloActionPerformed

    private void jMenuItem_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_generoActionPerformed
        String genero = JOptionPane.showInputDialog(this, "Informe o GÊNERO do filme","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        control.buscaFilme(genero, "genero");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_generoActionPerformed

    private void jMenuItem_duracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_duracaoActionPerformed
        String duracao = JOptionPane.showInputDialog(this, "Informe a DURAÇÃO do filme","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        
        control.buscaFilme(duracao, "duracao");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_duracaoActionPerformed

    private void jMenuItem_classificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_classificaActionPerformed
        String classif = (JOptionPane.showInputDialog(this, "Informe a CLASSIFICAÇÃO do filme\nOpções de classificação: L, 10, 12, 14, 16, 18","buscando cliente", JOptionPane.INFORMATION_MESSAGE)).toUpperCase();
        if(classif.equals("L")||classif.equals("10")||classif.equals("12")||classif.equals("14")||classif.equals("16")||classif.equals("18")){
            control.buscaFilme(classif, "classificacao");
            jTextArea_arquivoSalvo.setText(control.getTexto());
            jButton_encerrar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "CLASSIFICAÇÃO digitada inválida", "ERRO DE BUSCA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem_classificaActionPerformed

    private void jMenuItem_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_studioActionPerformed
        String studio = JOptionPane.showInputDialog(this, "Informe o STUDIO do filme","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        control.buscaFilme(studio, "studio");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_studioActionPerformed

    private void jMenuItem_alugadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_alugadoActionPerformed
        String alugado = JOptionPane.showInputDialog(this, "Informe o true para filme alugado\nou false para filme não alugado","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        control.buscaFilme(alugado.toLowerCase(), "alugado");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem_alugadoActionPerformed

    private void jTextField_duracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_duracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_duracaoActionPerformed

    private void jTextField_duracaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_duracaoKeyTyped
        
        
    }//GEN-LAST:event_jTextField_duracaoKeyTyped

    private void jTextField_duracaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_duracaoFocusLost
        
    }//GEN-LAST:event_jTextField_duracaoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_confirma;
    private javax.swing.JButton jButton_encerrar;
    private javax.swing.JCheckBox jCheckBox_filmeAlugado;
    private javax.swing.JComboBox<String> jComboBox_classificacao;
    private javax.swing.JLabel jLabel_classificacao;
    private javax.swing.JLabel jLabel_diretor;
    private javax.swing.JLabel jLabel_duracao;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_studioAntigo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_tituloAntigo;
    private javax.swing.JMenuBar jMenuBar_arquivo;
    private javax.swing.JMenuItem jMenuItem_alugado;
    private javax.swing.JMenuItem jMenuItem_classifica;
    private javax.swing.JMenuItem jMenuItem_duracao;
    private javax.swing.JMenuItem jMenuItem_editar;
    private javax.swing.JMenuItem jMenuItem_excluir;
    private javax.swing.JMenuItem jMenuItem_fechar;
    private javax.swing.JMenuItem jMenuItem_genero;
    private javax.swing.JMenuItem jMenuItem_salvar;
    private javax.swing.JMenuItem jMenuItem_studio;
    private javax.swing.JMenuItem jMenuItem_titulo;
    private javax.swing.JMenu jMenu_arquivos;
    private javax.swing.JMenu jMenu_buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_arquivoSalvo;
    private javax.swing.JTextField jTextField_diretor;
    private javax.swing.JTextField jTextField_duracao;
    private javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_titulo;
    // End of variables declaration//GEN-END:variables
}
