/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Cliente;

/**
 *
 * @author pedropereira
 */
public class ViewCliente extends javax.swing.JFrame {
    controller.ControllerCliente control = new controller.ControllerCliente();
    
    
    private void OpemCadCli(){
        jButton_confirm.setVisible(false);
        jButton_encerra.setVisible(false);
        control = new controller.ControllerCliente();
        control.setArquivo("clientes");
        if(control.ler()==true){
            jTextArea_arquivoSalvo.setText(control.getTexto());
        }
    }
    
    private void ClearFields(){
        jTextField_nome.setText("");
        jFormattedTextField_rg.setText("  .   .   - ");
        jTextField_endereco.setText("");
        jFormattedTextField_telefone.setText("  -9    -    ");
        jFormattedTextField_rg.setEnabled(true);
        OpemCadCli();
    }
    /**
     * Creates new form Cliente
     */
    public ViewCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nome = new javax.swing.JLabel();
        jLabel_rg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_arquivoSalvo = new javax.swing.JTextArea();
        jLabel_endereco = new javax.swing.JLabel();
        jLabel_telefone = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_endereco = new javax.swing.JTextField();
        jButton_confirm = new javax.swing.JButton();
        jButton_encerra = new javax.swing.JButton();
        jFormattedTextField_rg = new javax.swing.JFormattedTextField();
        jFormattedTextField_telefone = new javax.swing.JFormattedTextField();
        jMenuBar_arquivos = new javax.swing.JMenuBar();
        jMenu_file = new javax.swing.JMenu();
        jMenu_busca = new javax.swing.JMenu();
        jMenuItem_nome = new javax.swing.JMenuItem();
        jMenuItem_endereco = new javax.swing.JMenuItem();
        jMenuItem_telefone = new javax.swing.JMenuItem();
        jMenuItem_salvar = new javax.swing.JMenuItem();
        jMenuItem_editar = new javax.swing.JMenuItem();
        jMenuItem_excluir = new javax.swing.JMenuItem();
        jMenuItem_fechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento Cliente");
        setAlwaysOnTop(true);
        setFocusTraversalPolicyProvider(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel_nome.setText("NOME");

        jLabel_rg.setText("RG");
        jLabel_rg.setToolTipText("");

        jTextArea_arquivoSalvo.setEditable(false);
        jTextArea_arquivoSalvo.setColumns(20);
        jTextArea_arquivoSalvo.setRows(5);
        jScrollPane1.setViewportView(jTextArea_arquivoSalvo);

        jLabel_endereco.setText("ENDEREÇO");

        jLabel_telefone.setText("TELEFONE");

        jButton_confirm.setText(" Confirmar Edição");
        jButton_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmActionPerformed(evt);
            }
        });

        jButton_encerra.setText("Encerrar Busca");
        jButton_encerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_encerraActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jMenu_file.setText("Arquivo");

        jMenu_busca.setText("Buscar");

        jMenuItem_nome.setText("Por Nome");
        jMenuItem_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nomeActionPerformed(evt);
            }
        });
        jMenu_busca.add(jMenuItem_nome);

        jMenuItem_endereco.setText("Por Endereço");
        jMenuItem_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_enderecoActionPerformed(evt);
            }
        });
        jMenu_busca.add(jMenuItem_endereco);

        jMenuItem_telefone.setText("Por Telefone");
        jMenuItem_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_telefoneActionPerformed(evt);
            }
        });
        jMenu_busca.add(jMenuItem_telefone);

        jMenu_file.add(jMenu_busca);

        jMenuItem_salvar.setText("Salvar");
        jMenuItem_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_salvarActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_salvar);

        jMenuItem_editar.setText("Editar");
        jMenuItem_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_editarActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_editar);

        jMenuItem_excluir.setText("Excluir");
        jMenuItem_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_excluirActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_excluir);

        jMenuItem_fechar.setText("Fechar");
        jMenuItem_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_fecharActionPerformed(evt);
            }
        });
        jMenu_file.add(jMenuItem_fechar);

        jMenuBar_arquivos.add(jMenu_file);

        setJMenuBar(jMenuBar_arquivos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_endereco)
                                        .addComponent(jTextField_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel_endereco)))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel_telefone)
                                        .addGap(124, 124, 124))
                                    .addComponent(jFormattedTextField_rg)
                                    .addComponent(jFormattedTextField_telefone))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_rg)
                        .addGap(168, 168, 168))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton_confirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(jButton_encerra)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jLabel_rg))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_telefone)
                    .addComponent(jLabel_endereco))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_confirm)
                    .addComponent(jButton_encerra))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(775, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_salvarActionPerformed
        if(!jTextField_nome.getText().equals("")&&!jFormattedTextField_rg.getText().equals("  .   .   - ")&&!jTextField_endereco.getText().equals("")&&!jFormattedTextField_telefone.getText().equals("  -9    -    ")){
            control.setCliente(jTextField_nome.getText(), jFormattedTextField_rg.getText(), jTextField_endereco.getText(), jFormattedTextField_telefone.getText());
            if(!control.getTexto().equals("")){
                if(control.getCliText(jFormattedTextField_rg.getText())==null){
                    if(control.escrever(true)){
                        jTextArea_arquivoSalvo.setText(control.getTexto());
                        JOptionPane.showMessageDialog(this, "Arquivo escrito com sucesso","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                        jTextField_nome.setText("");
                        jFormattedTextField_rg.setText("  .   .   - ");
                        jTextField_endereco.setText("");
                        jFormattedTextField_telefone.setText("  -9    -    ");
                        OpemCadCli();
                    }else{
                        JOptionPane.showMessageDialog(this, "Escrita errada","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "RG já existe","ERROR", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                if(control.escrever(true)){
                    jTextArea_arquivoSalvo.setText(control.getTexto());
                    JOptionPane.showMessageDialog(this, "Arquivo escrito com sucesso","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                    jTextField_nome.setText("");
                    jFormattedTextField_rg.setText("  .   .   - ");
                    jTextField_endereco.setText("");
                    jFormattedTextField_telefone.setText("  -9     -    ");
                    OpemCadCli();
                }else{
                    JOptionPane.showMessageDialog(this, "Escrita errada","Escrita arquivo texto", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Todos Campos devem ser preenchidos","ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem_salvarActionPerformed

    private void jMenuItem_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_fecharActionPerformed
        ViewLocadora loc = new ViewLocadora();
        loc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem_fecharActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        OpemCadCli();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_editarActionPerformed
        jButton_confirm.setVisible(true);
        jFormattedTextField_rg.setText(JOptionPane.showInputDialog(this, "Informe o RG do cliente(sem pontos e traço)","buscando cliente", JOptionPane.INFORMATION_MESSAGE));
        Cliente cli = control.getCliText(jFormattedTextField_rg.getText());
        jFormattedTextField_rg.setText("  .   .   - ");
        if(cli == null){
            JOptionPane.showMessageDialog(this, "RG informado não encontrado", "ERRO DE BUSCA", JOptionPane.WARNING_MESSAGE);
            ClearFields();
        }else{
            jTextField_nome.setText(cli.getNome());
            jFormattedTextField_rg.setText(cli.getRg());
            jTextField_endereco.setText(cli.getEndereco());
            jFormattedTextField_telefone.setText(cli.getTelefone());
            jFormattedTextField_rg.setEnabled(false);
        }
    }//GEN-LAST:event_jMenuItem_editarActionPerformed

    private void jButton_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmActionPerformed
        control.editCliente(jTextField_nome.getText(), jFormattedTextField_rg.getText(), jTextField_endereco.getText(), jFormattedTextField_telefone.getText());
        ClearFields();
    }//GEN-LAST:event_jButton_confirmActionPerformed

    private void jMenuItem_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_excluirActionPerformed
        String rg = JOptionPane.showInputDialog(this, "Informe o RG do cliente(sem pontos e traço)","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        Cliente cli = control.getCliText(rg);
        if(cli == null){
            JOptionPane.showMessageDialog(this, "RG informado não encontrado", "ERRO DE BUSCA", JOptionPane.WARNING_MESSAGE);
        }else{
            if(JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o cliente: "+cli.getNome(),"EXCLUIR CLIENTE",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                control.excluiCliente(cli.getRg());
                ClearFields();
                JOptionPane.showMessageDialog(this, "Cliente Excluido com sucesso","AVISO",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Ação cancelada","AVISO",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem_excluirActionPerformed

    private void jMenuItem_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nomeActionPerformed
        String nome = JOptionPane.showInputDialog(this, "Informe o NOME do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        control.buscaCli(nome, "nome");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nomeActionPerformed

    private void jMenuItem_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_enderecoActionPerformed
        String endereco = JOptionPane.showInputDialog(this, "Informe o ENDEREÇO do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        control.buscaCli(endereco, "endereco");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_enderecoActionPerformed

    private void jMenuItem_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_telefoneActionPerformed
        jFormattedTextField_telefone.setText(JOptionPane.showInputDialog(this, "Informe o TELEFONE do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE));
        control.buscaCli(jFormattedTextField_telefone.getText(), "telefone");
        jFormattedTextField_telefone.setText("  -9    -    ");
        jTextArea_arquivoSalvo.setText(control.getTexto());
        jButton_encerra.setVisible(true);
    }//GEN-LAST:event_jMenuItem_telefoneActionPerformed

    private void jButton_encerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_encerraActionPerformed
        OpemCadCli();
    }//GEN-LAST:event_jButton_encerraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_confirm;
    private javax.swing.JButton jButton_encerra;
    private javax.swing.JFormattedTextField jFormattedTextField_rg;
    private javax.swing.JFormattedTextField jFormattedTextField_telefone;
    private javax.swing.JLabel jLabel_endereco;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_rg;
    private javax.swing.JLabel jLabel_telefone;
    private javax.swing.JMenuBar jMenuBar_arquivos;
    private javax.swing.JMenuItem jMenuItem_editar;
    private javax.swing.JMenuItem jMenuItem_endereco;
    private javax.swing.JMenuItem jMenuItem_excluir;
    private javax.swing.JMenuItem jMenuItem_fechar;
    private javax.swing.JMenuItem jMenuItem_nome;
    private javax.swing.JMenuItem jMenuItem_salvar;
    private javax.swing.JMenuItem jMenuItem_telefone;
    private javax.swing.JMenu jMenu_busca;
    private javax.swing.JMenu jMenu_file;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_arquivoSalvo;
    private javax.swing.JTextField jTextField_endereco;
    private javax.swing.JTextField jTextField_nome;
    // End of variables declaration//GEN-END:variables
}
