/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Pereira
 */
public class Janela01 extends javax.swing.JFrame {

    /**
     * Creates new form Janela01
     */
    public Janela01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_borda = new javax.swing.ButtonGroup();
        jButton_ola = new javax.swing.JButton();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jButton_Entrada = new javax.swing.JButton();
        jCheckBox_Borda = new javax.swing.JCheckBox();
        jCheckBox_Quijo = new javax.swing.JCheckBox();
        jCheckBox_Tomate = new javax.swing.JCheckBox();
        jButton_CheckBox = new javax.swing.JButton();
        jRadioButton_mussarela = new javax.swing.JRadioButton();
        jRadioButton_parmesao = new javax.swing.JRadioButton();
        jRadioButton_chedar = new javax.swing.JRadioButton();
        jButton_radio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_ola.setText("Clique Olá");
        jButton_ola.setToolTipText("");
        jButton_ola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_olaMouseClicked(evt);
            }
        });
        jButton_ola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_olaActionPerformed(evt);
            }
        });

        jLabel_nome.setText("Digite o seu nome");

        jButton_Entrada.setText("Entrar Nome");
        jButton_Entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EntradaMouseClicked(evt);
            }
        });
        jButton_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EntradaActionPerformed(evt);
            }
        });

        jCheckBox_Borda.setText("Borda recheada?");

        jCheckBox_Quijo.setText("Queijo extra?");

        jCheckBox_Tomate.setText("Tomates?");

        jButton_CheckBox.setText("Verifica Check Box");
        jButton_CheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CheckBoxMouseClicked(evt);
            }
        });

        buttonGroup_borda.add(jRadioButton_mussarela);
        jRadioButton_mussarela.setText("Borda Mussarela");

        buttonGroup_borda.add(jRadioButton_parmesao);
        jRadioButton_parmesao.setText("Borda Parmesao");

        buttonGroup_borda.add(jRadioButton_chedar);
        jRadioButton_chedar.setText("Borda Chedar");

        jButton_radio.setText("Verifica Radio Button");
        jButton_radio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_radioMouseClicked(evt);
            }
        });
        jButton_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_radioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_CheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton_radio)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_ola)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Entrada))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_nome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox_Borda)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox_Quijo)
                                        .addComponent(jCheckBox_Tomate)))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jRadioButton_chedar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton_mussarela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton_parmesao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nome)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ola)
                    .addComponent(jButton_Entrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Borda)
                    .addComponent(jRadioButton_mussarela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Quijo)
                    .addComponent(jRadioButton_parmesao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Tomate)
                    .addComponent(jRadioButton_chedar))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_radio)
                    .addComponent(jButton_CheckBox))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_olaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_olaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_olaActionPerformed

    private void jButton_olaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_olaMouseClicked
        String nome = jTextField_nome.getText();
        JOptionPane.showMessageDialog(this, "Olá "+nome+"!", "Mensagem de Boas Vindas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_olaMouseClicked

    private void jButton_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EntradaActionPerformed

    private void jButton_EntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EntradaMouseClicked
        String nome = " ";
        nome=JOptionPane.showInputDialog(this, "Digite o seu nome", "Boas Vindas", JOptionPane.QUESTION_MESSAGE);
        jTextField_nome.setText(nome);
    }//GEN-LAST:event_jButton_EntradaMouseClicked

    private void jButton_CheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CheckBoxMouseClicked
        boolean borda = jCheckBox_Borda.isSelected();
        boolean queijo = jCheckBox_Quijo.isSelected();
        boolean tomate = jCheckBox_Tomate.isSelected();
        String msg = "Pedido:\nBorda = "+borda+"\nQueijo = "+queijo+"\nTomate = "+tomate;
        JOptionPane.showMessageDialog(this, msg, "Pedido Pizza", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_CheckBoxMouseClicked

    private void jButton_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_radioActionPerformed

    private void jButton_radioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_radioMouseClicked
        boolean mussarela = jRadioButton_mussarela.isSelected();
        boolean parmesao = jRadioButton_parmesao.isSelected();
        boolean chedar = jRadioButton_chedar.isSelected();
        String msg = "Pedido:\nChedar = "+chedar+"\nParmesao = "+parmesao+"\nMussarela = "+mussarela;
        JOptionPane.showMessageDialog(this, msg, "Pedido Pizza", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_radioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_borda;
    private javax.swing.JButton jButton_CheckBox;
    private javax.swing.JButton jButton_Entrada;
    private javax.swing.JButton jButton_ola;
    private javax.swing.JButton jButton_radio;
    private javax.swing.JCheckBox jCheckBox_Borda;
    private javax.swing.JCheckBox jCheckBox_Quijo;
    private javax.swing.JCheckBox jCheckBox_Tomate;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JRadioButton jRadioButton_chedar;
    private javax.swing.JRadioButton jRadioButton_mussarela;
    private javax.swing.JRadioButton jRadioButton_parmesao;
    private javax.swing.JTextField jTextField_nome;
    // End of variables declaration//GEN-END:variables
}
