/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Pereira
 */


public class jFCalculadora extends javax.swing.JFrame {
    private int numFloat = 0;
    private int cont = 0;
    private int soma = 0;
    private int sub = 0;
    private int div = 0;
    private int mult = 0;
    private int result = 1;
    private double n1 = 0.0;
    private double n2 = 0.0;
    private int disable = 0;
    /**
     * Creates new form jFCalculadora
     */
    public jFCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_tela = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton_virgula = new javax.swing.JButton();
        jButton_resultado = new javax.swing.JButton();
        jButton_soma = new javax.swing.JButton();
        jButton_subtracao = new javax.swing.JButton();
        jButton_multiplicacao = new javax.swing.JButton();
        jButton_divisao = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jLabel_conta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(270, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(261, 300));

        jTextField_tela.setEditable(false);
        jTextField_tela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_tela.setText("0");

        jButton1.setText("1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("0");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton_virgula.setText(",");
        jButton_virgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_virgulaMouseClicked(evt);
            }
        });

        jButton_resultado.setText("=");
        jButton_resultado.setPreferredSize(new java.awt.Dimension(39, 23));
        jButton_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_resultadoMouseClicked(evt);
            }
        });

        jButton_soma.setText("+");
        jButton_soma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_somaMouseClicked(evt);
            }
        });

        jButton_subtracao.setText("-");
        jButton_subtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_subtracaoMouseClicked(evt);
            }
        });

        jButton_multiplicacao.setText("*");
        jButton_multiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_multiplicacaoMouseClicked(evt);
            }
        });

        jButton_divisao.setText("/");
        jButton_divisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_divisaoMouseClicked(evt);
            }
        });

        jButton_clear.setText("C");
        jButton_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_clearMouseClicked(evt);
            }
        });

        jLabel_conta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_tela, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_clear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2))
                            .addComponent(jButton10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton_virgula)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_subtracao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_divisao, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_multiplicacao, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_soma)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_tela, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_divisao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_multiplicacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_subtracao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton_soma))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton_virgula)
                    .addComponent(jButton_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disableBotoes(){
        jButton_divisao.enable(false);
        disable = 1;
    }
    
    private void enableBotoes(){
        jButton_divisao.enable(true);
        disable = 0;
    }
    
    private void clearVars(){
        numFloat = 0;
        cont = 0;
        soma = 0;
        sub = 0;
        div = 0;
        mult = 0;
        n1 = 0.0;
        n2 = 0.0;
        result = 1;
        jTextField_tela.setText("0");
        jLabel_conta.setText(" ");
        disable = 0;
    }
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(1));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(1));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(1));
            cont++;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(2));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(2));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(2));
            cont++;
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(3));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(3));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(3));
            cont++;
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(0));
            cont++;
        }
        else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(0));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(0));
            cont++;
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton_virgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_virgulaMouseClicked
        if(numFloat == 0)
        {
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(10));
            numFloat++;
            cont++;
        }
        if(result!=1){
            clearVars();
            jTextField_tela.setText("0"+controller.Calculadora.printNum(10));
            cont++;
        }
        
    }//GEN-LAST:event_jButton_virgulaMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(4));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(4));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(4));
            cont++;
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(5));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(5));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(5));
            cont++;
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(6));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(6));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(6));
            cont++;
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(7));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(7));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(7));
            cont++;
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(8));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(8));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(8));
            cont++;
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        if(cont == 0)
        {
            jTextField_tela.setText(controller.Calculadora.printNum(9));
            cont++;
        }else
            jTextField_tela.setText(jTextField_tela.getText()+controller.Calculadora.printNum(9));
        if(result!=1){
            clearVars();
            jTextField_tela.setText(controller.Calculadora.printNum(9));
            cont++;
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_clearMouseClicked
        clearVars();
    }//GEN-LAST:event_jButton_clearMouseClicked

    private void jButton_somaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_somaMouseClicked
        if(soma==0)
        {
            n1 = Double.parseDouble(jTextField_tela.getText());
            double verifica = Double.parseDouble("0.");
            if(n1 == verifica){
                jLabel_conta.setText("0"+" +");
                jTextField_tela.setText("0");
            }
            else
                jLabel_conta.setText(jTextField_tela.getText()+" +");
            
            soma++;
            cont = 0;
        }
        if(soma==1&&cont!=0){
            n2 = Double.parseDouble(jTextField_tela.getText());
            jTextField_tela.setText(String.valueOf(controller.Calculadora.soma(n1, n2)));
            jLabel_conta.setText(jTextField_tela.getText()+" +");
            n2 = Double.parseDouble(jTextField_tela.getText());
            cont = 0;
            result = 2;
        }
    }//GEN-LAST:event_jButton_somaMouseClicked

    private void jButton_subtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_subtracaoMouseClicked
        if(sub==0)
        {
            n1 = Double.parseDouble(jTextField_tela.getText());
            double verifica = Double.parseDouble("0.");
            if(n1 == verifica){
                jLabel_conta.setText("0"+" +");
                jTextField_tela.setText("0");
            }
            else
                jLabel_conta.setText(jTextField_tela.getText()+" -");
            
            sub++;
            cont = 0;
        }
        if(sub==1&&cont!=0){
            n2 = Double.parseDouble(jTextField_tela.getText());
            jTextField_tela.setText(String.valueOf(controller.Calculadora.subtracao(n1, n2)));
            jLabel_conta.setText(jTextField_tela.getText()+" -");
            n2 = Double.parseDouble(jTextField_tela.getText());
            cont = 0;
            result = 2;
        }
    }//GEN-LAST:event_jButton_subtracaoMouseClicked

    private void jButton_multiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_multiplicacaoMouseClicked
       if(mult==0)
        {
            n1 = Double.parseDouble(jTextField_tela.getText());
            double verifica = Double.parseDouble("0.");
            if(n1 == verifica){
                jLabel_conta.setText("0"+" *");
                jTextField_tela.setText("0");
            }
            else
                jLabel_conta.setText(jTextField_tela.getText()+" *");
            
            mult++;
            cont = 0;
        }
        if(mult==1&&cont!=0){
            n2 = Double.parseDouble(jTextField_tela.getText());
            jTextField_tela.setText(String.valueOf(controller.Calculadora.multiplicacao(n1, n2)));
            jLabel_conta.setText(jTextField_tela.getText()+" *");
            n2 = Double.parseDouble(jTextField_tela.getText());
            cont = 0;
            result = 2;
        }
    }//GEN-LAST:event_jButton_multiplicacaoMouseClicked

    private void jButton_divisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_divisaoMouseClicked
        if(div==0)
        {
            n1 = Double.parseDouble(jTextField_tela.getText());
            double verifica = Double.parseDouble("0.");
            if(n1 == verifica){
                jLabel_conta.setText("0"+" /");
                jTextField_tela.setText("0");
            }
            else
                jLabel_conta.setText(jTextField_tela.getText()+" /");
            
            div++;
            cont = 0;
        }
        if(div==1&&cont!=0){
            n2 = Double.parseDouble(jTextField_tela.getText());
            if(n1 == 0.0 && n2 == 0.0){
                jLabel_conta.setText(String.valueOf(n1)+" / "+jTextField_tela.getText()+" /");
                JOptionPane.showMessageDialog(this, "Resultado indefinido","ERROR",JOptionPane.WARNING_MESSAGE);
                jTextField_tela.setText("Resultado indefinido");
                disable = 1;
            }
            if(n1 != 0.0 && n2 == 0.0){
                jLabel_conta.setText(String.valueOf(n1)+" / ");
                JOptionPane.showMessageDialog(this, "Não é possível dividir por zero","ERROR",JOptionPane.WARNING_MESSAGE);
                jTextField_tela.setText("Não é possível dividir por zero");
                disable = 1;   
            }
            
            if(n1 != 0.0 && n2 != 0.0)
                {
                jTextField_tela.setText(String.valueOf(controller.Calculadora.subtracao(n1, n2)));
                jLabel_conta.setText(jTextField_tela.getText()+" /");
                n2 = Double.parseDouble(jTextField_tela.getText());
                cont = 0;
                result = 2;
            }
        }
    }//GEN-LAST:event_jButton_divisaoMouseClicked

    private void jButton_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_resultadoMouseClicked
        result--;
        
        if(disable == 1){
            clearVars();
        }
        
        if(result==0)
        {
            n2 = Double.parseDouble(jTextField_tela.getText());
            if(n1 == 0.0 && n2 == 0.0){
                jLabel_conta.setText(String.valueOf(n1)+" / "+jTextField_tela.getText()+" /");
                JOptionPane.showMessageDialog(this, "Resultado indefinido","ERROR",JOptionPane.WARNING_MESSAGE);
                jTextField_tela.setText("Resultado indefinido");
                disable = 1;
            }
            if(n1 != 0.0 && n2 == 0.0){
                jLabel_conta.setText(String.valueOf(n1)+" / ");
                JOptionPane.showMessageDialog(this, "Não é possível dividir por zero","ERROR",JOptionPane.WARNING_MESSAGE);
                jTextField_tela.setText("Não é possível dividir por zero");
                disable = 1;  
            }
            
            if(n1 != 0.0 && n2 != 0.0)
            {
                jLabel_conta.setText(jLabel_conta.getText()+" "+jTextField_tela.getText()+" = ");
                if(soma==1)
                    jTextField_tela.setText(String.valueOf(controller.Calculadora.soma(n1, n2)));
                if(sub==1)
                    jTextField_tela.setText(String.valueOf(controller.Calculadora.subtracao(n1, n2)));
                if(mult==1)
                    jTextField_tela.setText(String.valueOf(controller.Calculadora.multiplicacao(n1, n2)));
                if(div==1)
                    jTextField_tela.setText(String.valueOf(controller.Calculadora.divisao(n1, n2)));
                cont = 0;
                result = 2;
            }
            
            
            
            
        }
        
        if(result==1&&cont==0){
            jLabel_conta.setText("");
            n1 = Double.parseDouble(jTextField_tela.getText());
            if(soma!=0){
                jLabel_conta.setText(String.valueOf(n1)+" + "+String.valueOf(n2)+" =");
                jTextField_tela.setText(String.valueOf(controller.Calculadora.soma(n1, n2)));
            }
            
            if(sub!=0){
                jLabel_conta.setText(String.valueOf(n1)+" - "+String.valueOf(n2)+" =");
                jTextField_tela.setText(String.valueOf(controller.Calculadora.subtracao(n1, n2)));
            }
            
            if(mult!=0){
                jLabel_conta.setText(String.valueOf(n1)+" * "+String.valueOf(n2)+" =");
                jTextField_tela.setText(String.valueOf(controller.Calculadora.multiplicacao(n1, n2)));
            }
            
            if(div!=0){
                jLabel_conta.setText(String.valueOf(n1)+" / "+String.valueOf(n2)+" =");
                jTextField_tela.setText(String.valueOf(controller.Calculadora.divisao(n1, n2)));
            }

            //jTextField_tela.setText(jLabel_conta.getText());
            //cont = 0;
            result = 2;
        }
    }//GEN-LAST:event_jButton_resultadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_divisao;
    private javax.swing.JButton jButton_multiplicacao;
    private javax.swing.JButton jButton_resultado;
    private javax.swing.JButton jButton_soma;
    private javax.swing.JButton jButton_subtracao;
    private javax.swing.JButton jButton_virgula;
    private javax.swing.JLabel jLabel_conta;
    private javax.swing.JTextField jTextField_tela;
    // End of variables declaration//GEN-END:variables
}
