/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bancodados.JDBCUtil;
import controller.LocacaoDAO;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Locadora;
import utils.SoNumeros;

/**
 *
 * @author Pedro Pereira
 */
public class JanelaLocacoes extends javax.swing.JFrame {

    LocacaoDAO dao = new LocacaoDAO();
    
    public void BlockFields(String opcao){
        switch (opcao){
            case "empty":
                JFrame jcadLoca = new JanelaCadLocacao("new", null);
                this.dispose();
                jcadLoca.setVisible(true);
                break;
                
            case "search":
                btn_cancel.setEnabled(true);
                break;
                
            default:
                btn_anterior.setEnabled(true);
                btn_proximo.setEnabled(true);
                btn_primeiro.setEnabled(true);
                btn_ultimo.setEnabled(true);
                btn_inserir.setEnabled(true);
                btn_editar.setEnabled(true);
                btn_excluir.setEnabled(true);
                btn_cancel.setEnabled(false);
                jTF_id.setEnabled(false);
                jTF_funcionario.setEnabled(false);
                jTF_titulo.setEnabled(false);
                jTF_genero.setEnabled(false);
                jTF_studio.setEnabled(false);
                jTF_cliente.setEnabled(false);
                jTF_data.setEnabled(false);
                jTF_dtdevolucao.setEnabled(false);
                jTF_periodo.setEnabled(false);
                jTF_valor.setEnabled(false);
                jCB_devolvido.setEnabled(false);
                jM_busca.setEnabled(true);
                break;
        }
             
    }
    
    public void AtualizaBaseDados(int op){
        if(op==1){
            if (dao.ConsultarTodos()) {
                initComponents();
                BlockFields("");
                if (JDBCUtil.MovPrimeiro(dao.getRsdados())) {
                    ExibeRegistro(dao.getLocadora());
                }
            }else{
                JOptionPane.showMessageDialog(this, "Não há filmes registrados");
                BlockFields("empty");
            }
        }else{
            if (dao.ConsultarTodos()) {
                BlockFields("");
                if (JDBCUtil.MovPrimeiro(dao.getRsdados())) {
                    ExibeRegistro(dao.getLocadora());
                }
            }else{
                JOptionPane.showMessageDialog(this, "Não há filmes registrados");
                BlockFields("empty");
            }
        }
    }
    

    /**
     * Creates new form JanelaCliente
     */
    public JanelaLocacoes() {
        if (dao.CriaConexao()) {
            AtualizaBaseDados(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        btn_primeiro = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        jTF_genero = new javax.swing.JTextField();
        jTF_cliente = new javax.swing.JTextField();
        btn_inserir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_id = new javax.swing.JTextField();
        jTF_titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_studio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_funcionario = new javax.swing.JTextField();
        jTF_periodo = new javax.swing.JTextField();
        jTF_valor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCB_devolvido = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jTF_data = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_dtdevolucao = new javax.swing.JTextField();
        btn_Devolver = new javax.swing.JButton();
        btn_relatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_busca = new javax.swing.JMenu();
        jMI_titulo = new javax.swing.JMenuItem();
        jMI_genero = new javax.swing.JMenuItem();
        jMI_studio = new javax.swing.JMenuItem();
        jMI_cliente = new javax.swing.JMenuItem();
        jMI_data = new javax.swing.JMenuItem();
        jMI_periodo = new javax.swing.JMenuItem();
        jMI_valor = new javax.swing.JMenuItem();
        jMI_devolvido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locações");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("TITULO:");

        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("GENERO:");

        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("CLIENTE:");

        label5.setText("PERIODO:");

        btn_primeiro.setLabel("Primeiro");
        btn_primeiro.setName("btnprimeiro"); // NOI18N
        btn_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeiroActionPerformed(evt);
            }
        });

        btn_anterior.setText("<-");
        btn_anterior.setName("btnanterior"); // NOI18N
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_proximo.setText("->");
        btn_proximo.setName("btnproximo"); // NOI18N
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        btn_ultimo.setLabel("Último");
        btn_ultimo.setName("btnultimo"); // NOI18N
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        btn_inserir.setText("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("STUDIO:");

        jLabel3.setText("FUNCIONARIO:");

        jLabel4.setText("VALOR:");

        jCB_devolvido.setText("DEVOLVIDO");

        jLabel5.setText("DATA:");

        jLabel6.setText("DATA DEVOLUÇÃO:");

        btn_Devolver.setText("Devolver");
        btn_Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DevolverActionPerformed(evt);
            }
        });

        btn_relatorio.setText("Relatorio");
        btn_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relatorioActionPerformed(evt);
            }
        });

        jM_busca.setText("Buscar");
        jM_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_buscaActionPerformed(evt);
            }
        });

        jMI_titulo.setText("TITULO");
        jMI_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_tituloActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_titulo);

        jMI_genero.setText("GENERO");
        jMI_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_generoActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_genero);

        jMI_studio.setText("STUDIO");
        jMI_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_studioActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_studio);

        jMI_cliente.setText("CLIENTE");
        jMI_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_clienteActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_cliente);

        jMI_data.setText("DATA");
        jMI_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_dataActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_data);

        jMI_periodo.setText("PERIODO");
        jMI_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_periodoActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_periodo);

        jMI_valor.setText("VALOR");
        jMI_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_valorActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_valor);

        jMI_devolvido.setText("DEVOLVIDO");
        jMI_devolvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_devolvidoActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_devolvido);

        jMenuBar1.add(jM_busca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_funcionario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_genero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_anterior)
                        .addGap(18, 18, 18)
                        .addComponent(btn_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_data, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_dtdevolucao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_studio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jCB_devolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_inserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_relatorio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Devolver)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_primeiro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_anterior)
                        .addComponent(btn_proximo)
                        .addComponent(btn_ultimo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTF_dtdevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jCB_devolvido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_relatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inserir)
                    .addComponent(btn_editar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_cancel)
                    .addComponent(btn_Devolver))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeiroActionPerformed
        if (JDBCUtil.MovPrimeiro(dao.getRsdados())) {
            ExibeRegistro(dao.getLocadora());
            //AtualizaBaseDados(2);
        } else {
            JOptionPane.showMessageDialog(this, "O primeiro registro ja esta selecionado.");
        }
    }//GEN-LAST:event_btn_primeiroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        if (JDBCUtil.MovAnterior(dao.getRsdados())) {
            ExibeRegistro(dao.getLocadora());
            //AtualizaBaseDados(2);
        } else {
            JOptionPane.showMessageDialog(this, "Nao existe registro anterior.");
        }
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        if (JDBCUtil.MovProximo(dao.getRsdados())) {
            ExibeRegistro(dao.getLocadora());
            //AtualizaBaseDados(2);
        } else {
            JOptionPane.showMessageDialog(this, "Nao existe proximo elemento.");
        }
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        if (JDBCUtil.MovUltimo(dao.getRsdados())) {
            ExibeRegistro(dao.getLocadora());
            //AtualizaBaseDados(2);
        } else {
            JOptionPane.showMessageDialog(this, "O ultimo registro ja esta selecionado.");
        }
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        JFrame jcadLoca = new JanelaCadLocacao("new", null);
        this.dispose();
        jcadLoca.setVisible(true);
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dao.FechaConexao();
        JFrame jpri = new JanelaPrincipal();
        jpri.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        Locadora loc = CarregaLocacao();
        JFrame jcadLoca = new JanelaCadLocacao("edit", CarregaLocacao());
        this.dispose();
        jcadLoca.setVisible(true);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Locadora loc = CarregaLocacao();
        if (dao.Excluir(loc)) {
            JOptionPane.showMessageDialog(this, "Locacao excluída com sucesso.");
            AtualizaBaseDados(2);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a locacao.");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        AtualizaBaseDados(2);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jM_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_buscaActionPerformed
        
    }//GEN-LAST:event_jM_buscaActionPerformed

    private void jMI_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_tituloActionPerformed
        String titulo = JOptionPane.showInputDialog(this, "Informe o TITULO do filme","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        if(dao.ConsultarTitulo(titulo)){
            JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
            ExibeRegistro(dao.getLocadora());
            btn_primeiroActionPerformed(evt);
            BlockFields("search");
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum filme foi encontrado.");
            AtualizaBaseDados(2);
        }
    }//GEN-LAST:event_jMI_tituloActionPerformed

    private void jMI_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_generoActionPerformed
        String genero = JOptionPane.showInputDialog(this, "Informe o GENERO do filme","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        if(dao.ConsultarGenero(genero)){
            JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
            ExibeRegistro(dao.getLocadora());
            btn_primeiroActionPerformed(evt);
            BlockFields("search");
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum filme foi encontrado.");
            AtualizaBaseDados(2);
        }
    }//GEN-LAST:event_jMI_generoActionPerformed

    private void jMI_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_clienteActionPerformed
        String cpf = JOptionPane.showInputDialog(this, "Informe o CPF do cliente","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        cpf=dao.TrataCpf(cpf);
        if(dao.ConsultarCliente(cpf)){
            JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
            btn_primeiroActionPerformed(evt);
            BlockFields("search");
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma locacao foi encontrado.");
            AtualizaBaseDados(2);
        }
    }//GEN-LAST:event_jMI_clienteActionPerformed

    private void jMI_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_dataActionPerformed
        String data = JOptionPane.showInputDialog(this, "Informe o CPF do cliente","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        data=dao.TrataData(data);
        if(dao.ConsultarData(data)){
            JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
            btn_primeiroActionPerformed(evt);
            BlockFields("search");
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma locacao foi encontrado.");
            AtualizaBaseDados(2);
        }
    }//GEN-LAST:event_jMI_dataActionPerformed

    private void jMI_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_studioActionPerformed
        String studio = JOptionPane.showInputDialog(this, "Informe o STUDIO do filme","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        if(dao.ConsultarStudio(studio)){
            JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
            ExibeRegistro(dao.getLocadora());
            btn_primeiroActionPerformed(evt);
            BlockFields("search");
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum filme foi encontrado.");
            AtualizaBaseDados(2);
        }
    }//GEN-LAST:event_jMI_studioActionPerformed

    private void btn_DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DevolverActionPerformed
        Locadora loc = CarregaLocacao();
        if(dao.BuscaDevolvidos(Integer.parseInt(jTF_id.getText()),false)){
            if(dao.Devolver(loc)){
                JOptionPane.showMessageDialog(this, "Locacao devolvida com sucesso.");
                AtualizaBaseDados(2);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao devolver a locacao.");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Locacao já foi devolvida.");
        }
    }//GEN-LAST:event_btn_DevolverActionPerformed

    private void jMI_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_periodoActionPerformed
        String periodo = JOptionPane.showInputDialog(this, "Informe o PERIODO do filme","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        if (periodo.substring(0).matches("[A-Z]*") || periodo.substring(0).matches("[a-z]*") || (!periodo.equals("1") && !periodo.equals("2") && !periodo.equals("3")) || periodo.length()>1){
            JOptionPane.showMessageDialog(this, "Periodo inserido é inválido.");
        }else{
            if(dao.ConsultarPeriodo(Integer.parseInt(periodo))){
                JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
                ExibeRegistro(dao.getLocadora());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum filme foi encontrado.");
                AtualizaBaseDados(2);
            }
        }
    }//GEN-LAST:event_jMI_periodoActionPerformed

    private void jMI_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_valorActionPerformed
        String valor = JOptionPane.showInputDialog(this, "Informe o VALOR do filme","buscando filme", JOptionPane.INFORMATION_MESSAGE);
        if (valor.substring(0).matches("[A-Z]*") || valor.substring(0).matches("[a-z]*")){
            JOptionPane.showMessageDialog(this, "Periodo inserido é inválido.");
        }else{
            if(dao.ConsultarValor(Float.valueOf(valor))){
                JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
                ExibeRegistro(dao.getLocadora());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum filme foi encontrado.");
                AtualizaBaseDados(2);
            }
        }
    }//GEN-LAST:event_jMI_valorActionPerformed

    private void jMI_devolvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_devolvidoActionPerformed
        String devolvido = (JOptionPane.showInputDialog(this, "Informe o DEVOLVIDO do filme","buscando filme", JOptionPane.INFORMATION_MESSAGE)).toUpperCase();
        if (!devolvido.equals("FALSE") && !devolvido.equals("TRUE")) {
            JOptionPane.showMessageDialog(this, "Periodo inserido é inválido.");
        }else{
            if(dao.ConsultarDevolvido(Boolean.valueOf(devolvido))){
                JOptionPane.showMessageDialog(this, "Locacoes(s) encontrada(s) com sucesso.");
                ExibeRegistro(dao.getLocadora());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum filme foi encontrado.");
                AtualizaBaseDados(2);
            }
        }
    }//GEN-LAST:event_jMI_devolvidoActionPerformed

    private void btn_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relatorioActionPerformed
        JFrame jrelat = new JanelaRelatorioLocacao();
        jrelat.setVisible(true);
    }//GEN-LAST:event_btn_relatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaLocacoes().setVisible(true);
            }
        });
    }

    public void ExibeRegistro(Locadora loc) {
        //faz a leitura do objeto cliente e atribui os valores lidos aos objetos visuais (Textfields)
        jTF_id.setText(String.valueOf(loc.getId()));
        jTF_funcionario.setText(loc.getFuncionario());
        jTF_titulo.setText(loc.getTituloFilme());
        jTF_genero.setText(loc.getGeneroFilme());
        jTF_studio.setText(loc.getStudioFilme());
        jTF_cliente.setText(loc.getCpfCliente());
        jTF_data.setText(loc.getData());
        jTF_dtdevolucao.setText(loc.getDataDevolucao());
        jTF_periodo.setText(String.valueOf(loc.getPeriodoAlugado()));
        jTF_valor.setText(String.valueOf(loc.getValor()));
        if(loc.getDevolvido()){
            jCB_devolvido.setSelected(true);
            btn_Devolver.setEnabled(false);
        }
        else{
            jCB_devolvido.setSelected(false);
            btn_Devolver.setEnabled(true);
        }
    }

    public Locadora CarregaLocacao() {
        //faz a leitura dos valores da janela em um objeto Cliente
        Locadora locadora = null;
        int id = Integer.parseInt(jTF_id.getText());
        String funcionario = jTF_funcionario.getText();
        String titulo = jTF_titulo.getText();
        String genero = jTF_genero.getText();
        String studio = jTF_studio.getText();
        String cpf = jTF_cliente.getText();
        String data = jTF_data.getText();
        String dataDevolv = jTF_dtdevolucao.getText();
        int periodo = Integer.valueOf(String.valueOf(jTF_periodo.getText()));
        float valor = Float.valueOf(String.valueOf(jTF_valor.getText()));
        boolean devolvido = false;
        if(jCB_devolvido.isSelected())
            devolvido = true;
        else
            devolvido = false;
        
        locadora = new Locadora(id, funcionario, titulo, genero, studio, cpf, data, dataDevolv, periodo, valor, devolvido);
        return locadora;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Devolver;
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JButton btn_primeiro;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_relatorio;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JCheckBox jCB_devolvido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMI_cliente;
    private javax.swing.JMenuItem jMI_data;
    private javax.swing.JMenuItem jMI_devolvido;
    private javax.swing.JMenuItem jMI_genero;
    private javax.swing.JMenuItem jMI_periodo;
    private javax.swing.JMenuItem jMI_studio;
    private javax.swing.JMenuItem jMI_titulo;
    private javax.swing.JMenuItem jMI_valor;
    private javax.swing.JMenu jM_busca;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTF_cliente;
    private javax.swing.JTextField jTF_data;
    private javax.swing.JTextField jTF_dtdevolucao;
    private javax.swing.JTextField jTF_funcionario;
    private javax.swing.JTextField jTF_genero;
    private javax.swing.JTextField jTF_id;
    private javax.swing.JTextField jTF_periodo;
    private javax.swing.JTextField jTF_studio;
    private javax.swing.JTextField jTF_titulo;
    private javax.swing.JTextField jTF_valor;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    // End of variables declaration//GEN-END:variables
}
