/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import model.Cliente;
import controller.ClienteDAO;
import bancodados.JDBCUtil;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Pereira
 */
public class JanelaCliente extends javax.swing.JFrame {

    ClienteDAO dao = new ClienteDAO();
    private int contEdit = 0;
    private int contNew = 0;
    private String nome = "";
    private String endereco = "";
    private String telefone = "";
    
    public void BlockFields(String opcao){
        switch (opcao){
            case "edit":
                btn_anterior.setEnabled(false);
                btn_proximo.setEnabled(false);
                btn_primeiro.setEnabled(false);
                btn_ultimo.setEnabled(false);
                btn_inserir.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancel.setEnabled(true);
                jTF_cpf.setEnabled(true);
                jTF_nome.setEnabled(true);
                jTF_idade.setEnabled(true);
                jTF_fone.setEnabled(true);
                jM_busca.setEnabled(false);
                contEdit = 1;
                break;
                
            case "new":
                btn_anterior.setEnabled(false);
                btn_proximo.setEnabled(false);
                btn_primeiro.setEnabled(false);
                btn_ultimo.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancel.setEnabled(true);
                jTF_cpf.setEnabled(true);
                jTF_nome.setEnabled(true);
                jTF_idade.setEnabled(true);
                jTF_fone.setEnabled(true);
                jM_busca.setEnabled(false);
                contNew = 1;
                break;
                
            case "empty":
                btn_anterior.setEnabled(false);
                btn_proximo.setEnabled(false);
                btn_primeiro.setEnabled(false);
                btn_ultimo.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancel.setEnabled(false);
                btn_inserir.setEnabled(true);
                jM_busca.setEnabled(false);
                jTF_cpf.setEnabled(true);
                jTF_nome.setEnabled(true);
                jTF_idade.setEnabled(true);
                jTF_fone.setEnabled(true);
                jTF_id.setEnabled(false);
                jTF_id.setText("0");
                jTF_cpf.setText("");
                jTF_nome.setText("");
                jTF_idade.setText("");
                jTF_fone.setText("");
                contNew = 1;
                break;
                
            case "search":
                btn_cancel.setEnabled(true);
                break;
                
            default:
                btn_anterior.setEnabled(true);
                btn_proximo.setEnabled(true);
                btn_primeiro.setEnabled(true);
                btn_ultimo.setEnabled(true);
                btn_inserir.setEnabled(true);
                btn_editar.setEnabled(true);
                btn_excluir.setEnabled(true);
                btn_cancel.setEnabled(false);
                jTF_cpf.setEnabled(false);
                jTF_nome.setEnabled(false);
                jTF_idade.setEnabled(false);
                jTF_fone.setEnabled(false);
                jTF_id.setEnabled(false);
                jM_busca.setEnabled(true);
                nome = "";
                endereco = "";
                telefone = "";
                contEdit = 0;
                contNew = 0;
                break;
        }
             
    }
    
    public void AtualizaBaseDados(){
        if (dao.ConsultarTodos()) {
            BlockFields("");
            if (JDBCUtil.MovPrimeiro(dao.getRsdados())) {
                ExibeRegistro(dao.getCliente());
            }
        }else{
            BlockFields("empty");
            JOptionPane.showMessageDialog(this, "Não há clientes registrados");
        }
    }
    

    /**
     * Creates new form JanelaCliente
     */
    public JanelaCliente() {
        initComponents();
        if (dao.CriaConexao()) {
            AtualizaBaseDados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        btn_primeiro = new javax.swing.JButton();
        btn_anterior = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        jTF_nome = new javax.swing.JTextField();
        jTF_idade = new javax.swing.JTextField();
        btn_inserir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_id = new javax.swing.JTextField();
        jTF_cpf = new javax.swing.JFormattedTextField();
        jTF_fone = new javax.swing.JFormattedTextField();
        btn_relatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_busca = new javax.swing.JMenu();
        jMI_cpf = new javax.swing.JMenuItem();
        jMI_nome = new javax.swing.JMenuItem();
        jMI_endereco = new javax.swing.JMenuItem();
        jMI_telefone = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("CPF:");

        label3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label3.setText("nome:");

        label4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label4.setText("endereço:");

        label5.setText("fone:");

        btn_primeiro.setLabel("Primeiro");
        btn_primeiro.setName("btnprimeiro"); // NOI18N
        btn_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_primeiroActionPerformed(evt);
            }
        });

        btn_anterior.setText("<-");
        btn_anterior.setName("btnanterior"); // NOI18N
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });

        btn_proximo.setText("->");
        btn_proximo.setName("btnproximo"); // NOI18N
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        btn_ultimo.setLabel("Último");
        btn_ultimo.setName("btnultimo"); // NOI18N
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });

        btn_inserir.setText("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Id:");

        try {
            jTF_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTF_fone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btn_relatorio.setText("Relatorio");
        btn_relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_relatorioActionPerformed(evt);
            }
        });

        jM_busca.setText("Buscar");
        jM_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_buscaActionPerformed(evt);
            }
        });

        jMI_cpf.setText("CPF");
        jMI_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_cpfActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_cpf);

        jMI_nome.setText("NOME");
        jMI_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_nomeActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_nome);

        jMI_endereco.setText("ENDEREÇO");
        jMI_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_enderecoActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_endereco);

        jMI_telefone.setText("TELEFONE");
        jMI_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_telefoneActionPerformed(evt);
            }
        });
        jM_busca.add(jMI_telefone);

        jMenuBar1.add(jM_busca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btn_anterior)
                                .addGap(18, 18, 18)
                                .addComponent(btn_proximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ultimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTF_idade, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                    .addComponent(jTF_nome)
                                    .addComponent(jTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_relatorio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(label5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_primeiro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_anterior)
                        .addComponent(btn_proximo)
                        .addComponent(btn_ultimo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inserir)
                    .addComponent(btn_editar)
                    .addComponent(btn_excluir)
                    .addComponent(btn_cancel)
                    .addComponent(btn_relatorio))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_primeiroActionPerformed
        if (JDBCUtil.MovPrimeiro(dao.getRsdados())) {
            ExibeRegistro(dao.getCliente());
        } else {
            JOptionPane.showMessageDialog(this, "O primeiro registro ja esta selecionado.");
        }
    }//GEN-LAST:event_btn_primeiroActionPerformed

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        if (JDBCUtil.MovAnterior(dao.getRsdados())) {
            ExibeRegistro(dao.getCliente());
        } else {
            JOptionPane.showMessageDialog(this, "Nao existe registro anterior.");
        }
    }//GEN-LAST:event_btn_anteriorActionPerformed

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed
        if (JDBCUtil.MovProximo(dao.getRsdados())) {
            ExibeRegistro(dao.getCliente());
        } else {
            JOptionPane.showMessageDialog(this, "Nao existe proximo elemento.");
        }
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        if (JDBCUtil.MovUltimo(dao.getRsdados())) {
            ExibeRegistro(dao.getCliente());
        } else {
            JOptionPane.showMessageDialog(this, "O ultimo registro ja esta selecionado.");
        }
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        Cliente cli = CarregaCliente();
        if(contNew==1){
            int resp = dao.validaCliente(cli);
            if(resp == 0){
                if (dao.Inserir(cli)) {
                    JOptionPane.showMessageDialog(this, "Cliente inserido com sucesso.");
                    AtualizaBaseDados();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir cliente.");
                }
            }else if(resp == 1){
                JOptionPane.showMessageDialog(this, "CPF inserido já está cadastrado.");
            }else if(resp == 2){
                JOptionPane.showMessageDialog(this, "CPF inserido é inválido.");
            }
            else if(resp == 3){
                JOptionPane.showMessageDialog(this, "Nome inserido é inválido.");
            }
            else if(resp == 4){
                JOptionPane.showMessageDialog(this, "Endereço inserido é inválido.");
            }
            else if(resp == 5){
                JOptionPane.showMessageDialog(this, "Telefone inserido é inválido.");
            }
        }else{
            jTF_cpf.setText("");
            jTF_nome.setText("");
            jTF_idade.setText("");
            jTF_fone.setText("");
            jTF_cpf.requestFocus();
            BlockFields("new");
        }
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dao.FechaConexao();
        JFrame jpri = new JanelaPrincipal();
        jpri.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        Cliente cli = CarregaCliente();
        if(contEdit==1){
            if (dao.Alterar(cli)) {
                JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso.");
                AtualizaBaseDados();
                BlockFields("");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar cliente.");
            }
        }else{
            BlockFields("edit");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        Cliente cli = CarregaCliente();
        if (dao.Excluir(cli)) {
            JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso.");
            AtualizaBaseDados();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir cliente.");
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        AtualizaBaseDados();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jM_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_buscaActionPerformed
        
    }//GEN-LAST:event_jM_buscaActionPerformed

    private void jMI_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_cpfActionPerformed
        jTF_cpf.setText("");
        String cpf = JOptionPane.showInputDialog(this, "Informe o CPF do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        jTF_cpf.setText(cpf);
        Cliente cli = dao.ConsultarCpf(jTF_cpf.getText());
        if(cli!=null){
            JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
            ExibeRegistro(cli);
            btn_primeiroActionPerformed(evt);
            BlockFields("search");
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
            AtualizaBaseDados();
        }
            
    }//GEN-LAST:event_jMI_cpfActionPerformed

    private void jMI_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_nomeActionPerformed
        nome = JOptionPane.showInputDialog(this, "Informe o NOME do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        if(endereco.equals("")&&telefone.equals("")){
            if(dao.ConsultarNome(nome)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }else if(!endereco.equals("")){
            if(dao.ConsultarAninhadaNomeEndereco(nome, endereco)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }else if(!telefone.equals("")){
            if(dao.ConsultarAninhadaNomeTelefone(nome, endereco)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }
    }//GEN-LAST:event_jMI_nomeActionPerformed

    private void jMI_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_enderecoActionPerformed
        endereco = JOptionPane.showInputDialog(this, "Informe o ENDERECO do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        if(nome.equals("")&&telefone.equals("")){
            if(dao.ConsultarEndereco(endereco)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }else if(!nome.equals("")){
            if(dao.ConsultarAninhadaNomeEndereco(nome, endereco)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }else if(!telefone.equals("")){
            if(dao.ConsultarAninhadaEnderecoTelefone(endereco, telefone)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }
    }//GEN-LAST:event_jMI_enderecoActionPerformed

    private void jMI_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_telefoneActionPerformed
        telefone = JOptionPane.showInputDialog(this, "Informe o ENDERECO do cliente","buscando cliente", JOptionPane.INFORMATION_MESSAGE);
        if(nome.equals("")&&endereco.equals("")){
            if(dao.ConsultarTelefone(telefone)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }else if(!nome.equals("")){
            if(dao.ConsultarAninhadaNomeTelefone(nome, telefone)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }else if(!endereco.equals("")){
            if(dao.ConsultarAninhadaEnderecoTelefone(endereco, telefone)){
                JOptionPane.showMessageDialog(this, "Cliente(s) encontrado(s) com sucesso.");
                ExibeRegistro(dao.getCliente());
                btn_primeiroActionPerformed(evt);
                BlockFields("search");
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum cliente foi encontrado.");
                AtualizaBaseDados();
            }
        }
    }//GEN-LAST:event_jMI_telefoneActionPerformed

    private void btn_relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_relatorioActionPerformed
        //dao.FechaConexao();
        JFrame jrelat = new JanelaRelatorioCli();
        jrelat.setVisible(true);
    }//GEN-LAST:event_btn_relatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCliente().setVisible(true);
            }
        });
    }

    public void ExibeRegistro(Cliente cli) {
        //faz a leitura do objeto cliente e atribui os valores lidos aos objetos visuais (Textfields)
        jTF_id.setText(String.valueOf(cli.getId()));
        jTF_cpf.setText(cli.getCpf());
        jTF_nome.setText(cli.getNome());
        jTF_idade.setText(cli.getEndereco());
        jTF_fone.setText(cli.getTelefone());
    }

    public Cliente CarregaCliente() {
        //faz a leitura dos valores da janela em um objeto Cliente
        Cliente cli = null;
        int id = Integer.parseInt(jTF_id.getText());
        String cpf = jTF_cpf.getText();
        String nome = jTF_nome.getText();
        String endereco = jTF_idade.getText();
        String telefone = jTF_fone.getText();
        cli = new Cliente(id,cpf, nome, endereco, telefone);
        return cli;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JButton btn_primeiro;
    private javax.swing.JButton btn_proximo;
    private javax.swing.JButton btn_relatorio;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMI_cpf;
    private javax.swing.JMenuItem jMI_endereco;
    private javax.swing.JMenuItem jMI_nome;
    private javax.swing.JMenuItem jMI_telefone;
    private javax.swing.JMenu jM_busca;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JFormattedTextField jTF_cpf;
    private javax.swing.JFormattedTextField jTF_fone;
    private javax.swing.JTextField jTF_id;
    private javax.swing.JTextField jTF_idade;
    private javax.swing.JTextField jTF_nome;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    // End of variables declaration//GEN-END:variables
}
