/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import bancodados.JDBCUtil;
import controller.LocacaoDAO;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Filme;
import model.Locadora;
import utils.SoNumeros;

/**
 *
 * @author Pedro Pereira
 */
public class JanelaCadLocacao extends javax.swing.JFrame {

    LocacaoDAO dao = new LocacaoDAO();
    Locadora loc = null;
    
    public void BlockFields(String opcao){
        switch (opcao){
            case "edit":
                jTF_id.setEnabled(false);
                btn_inserir.setEnabled(false);
                btn_cancel.setEnabled(true);
                btn_editar.setEnabled(true);
                jTF_genero.setEnabled(false);
                jTF_studio.setEnabled(false);
                ExibeTitulo();
                ExibeCliente();
                ExibeRegistro(this.loc);
                break;
                
            case "new":
                jTF_id.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_cancel.setEnabled(true);
                btn_inserir.setEnabled(true);
                jTF_genero.setEnabled(false);
                jTF_studio.setEnabled(false);
                jCB_devolvido.setEnabled(false);
                jTF_id.setText("0");
                jTF_func.requestFocus();
                ExibeTitulo();
                ExibeCliente();
                break;
        }
             
    }   

    /**
     * Creates new form JanelaCliente
     */
    public JanelaCadLocacao(String tipo, Locadora loc) {
        initComponents();
        //jTF_duracao.setDocument(new SoNumeros());
        this.loc = loc;
        if (dao.CriaConexao()) {
            BlockFields(tipo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        btn_inserir = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_id = new javax.swing.JTextField();
        jCB_periodo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF_func = new javax.swing.JTextField();
        jCB_titulo = new javax.swing.JComboBox<>();
        jCB_cpf = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTF_valor = new javax.swing.JTextField();
        jCB_devolvido = new javax.swing.JCheckBox();
        jTF_genero = new javax.swing.JTextField();
        jTF_studio = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Locações");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("TITULO:");

        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("GENERO:");

        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("CLIENTE:");

        label5.setText("PERIODO:");

        btn_inserir.setText("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancelar");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jTF_id.setText("0");

        jCB_periodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel2.setText("STUDIO:");

        jLabel3.setText("FUNCIONÁRIO:");

        jCB_titulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jCB_titulo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCB_tituloItemStateChanged(evt);
            }
        });
        jCB_titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCB_tituloMouseClicked(evt);
            }
        });

        jCB_cpf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel4.setText("VALOR:");

        jCB_devolvido.setText("DEVOLVIDO");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_func))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCB_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jCB_devolvido, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_cancel)))
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF_genero)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_studio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_func, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_devolvido))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inserir)
                    .addComponent(btn_editar)
                    .addComponent(btn_cancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        Locadora locadora = CarregaLocacao();
        int resp = dao.validaLocadora(locadora, 1);
        if(resp == 0){
            if (dao.Inserir(locadora)) {
                JOptionPane.showMessageDialog(this, "Filme alugado com sucesso.");
                FecharJanela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alugar filme.");
            }
        }else if(resp == 1){
            JOptionPane.showMessageDialog(this, "Filme inserido já está alugado.");
        }else if(resp == 2){
            JOptionPane.showMessageDialog(this, "Funcionário inserido é inválido.");
        }else if(resp == 3){
            JOptionPane.showMessageDialog(this, "Titulo inserido é inválido.");
        }
        else if(resp == 4){
            JOptionPane.showMessageDialog(this, "Gênero inserido é inválido.");
        }
        else if(resp == 5){
            JOptionPane.showMessageDialog(this, "Studio inserida é inválida.");
        }
        else if(resp == 6){
            JOptionPane.showMessageDialog(this, "CPF inserido é inválido.");
        }
        else if(resp == 7){
            JOptionPane.showMessageDialog(this, "Valor inserido é inválido.");
        }
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FecharJanela();
    }//GEN-LAST:event_formWindowClosing

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int resp = 0;
        if(loc.getTituloFilme().equals(String.valueOf(jCB_titulo.getSelectedItem())) && loc.getGeneroFilme().equals(jTF_genero.getText()) && loc.getStudioFilme().equals(jTF_studio.getText())){
            loc = CarregaLocacao();
            resp = dao.validaLocadora(loc, 0);
        }else{
            resp = dao.validaLocadora(loc, 1);
        }
        if(resp == 0){
            if (dao.Alterar(loc)) {
                JOptionPane.showMessageDialog(this, "Locacao alterada com sucesso.");
                FecharJanela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar a locacao.");
            }
        }else if(resp == 1){
            JOptionPane.showMessageDialog(this, "Filme inserido já está alugado.");
        }else if(resp == 2){
            JOptionPane.showMessageDialog(this, "Funcionário inserido é inválido.");
        }else if(resp == 3){
            JOptionPane.showMessageDialog(this, "Titulo inserido é inválido.");
        }
        else if(resp == 4){
            JOptionPane.showMessageDialog(this, "Gênero inserido é inválido.");
        }
        else if(resp == 5){
            JOptionPane.showMessageDialog(this, "Studio inserida é inválida.");
        }
        else if(resp == 6){
            JOptionPane.showMessageDialog(this, "CPF inserido é inválido.");
        }
        else if(resp == 7){
            JOptionPane.showMessageDialog(this, "Valor inserido é inválido.");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        FecharJanela();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void jCB_tituloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCB_tituloItemStateChanged
        if(!String.valueOf(jCB_titulo.getSelectedItem()).equals("")){
            if(dao.getFilmePreenche(String.valueOf(jCB_titulo.getSelectedItem()))){
                Filme fil = dao.getFilme();
                jTF_genero.setText(fil.getGenero());
                jTF_studio.setText(fil.getStudio());
            }
        }
    }//GEN-LAST:event_jCB_tituloItemStateChanged

    private void jCB_tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCB_tituloMouseClicked
               
    }//GEN-LAST:event_jCB_tituloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadLocacao("", null).setVisible(true);
            }
        });
    }

    public void ExibeRegistro(Locadora locadora) {
        //faz a leitura do objeto cliente e atribui os valores lidos aos objetos visuais (Textfields)
        jTF_id.setText(String.valueOf(locadora.getId()));
        jTF_func.setText(locadora.getFuncionario());
        jCB_titulo.setSelectedItem(locadora.getTituloFilme());
        jTF_genero.setText(locadora.getGeneroFilme());
        jTF_studio.setText(locadora.getStudioFilme());
        jCB_cpf.setSelectedItem(locadora.getCpfCliente());
        jCB_periodo.setSelectedItem(locadora.getPeriodoAlugado());
        jTF_valor.setText(String.valueOf(locadora.getValor()));
        if(loc.getDevolvido())
            jCB_devolvido.setSelected(true);
        else
            jCB_devolvido.setSelected(false);
    }
    
    public void ExibeTitulo() {
        //faz a leitura do objeto cliente e atribui os valores lidos aos objetos visuais (Textfields)
        try{
            if(dao.getTodosTitulos()){
                String fil = dao.getTitulo();
                while(!fil.equals("")){
                    jCB_titulo.addItem(fil);
                    fil = dao.getTitulo();
                }
            }
        } catch (NullPointerException err) {
            System.out.println(err);
        }
    }
    
   public void ExibeCliente() {
        //faz a leitura do objeto cliente e atribui os valores lidos aos objetos visuais (Textfields)
        try{
            if(dao.getTodosClientes()){
                String fil = dao.getCpf();
                while(!fil.equals("")){
                    jCB_cpf.addItem(fil);
                    fil = dao.getCpf();
                }
            }
        } catch (NullPointerException err) {
            System.out.println(err);
        }
    }

    public Locadora CarregaLocacao() {
        //faz a leitura dos valores da janela em um objeto Cliente
        Locadora locadora = null;
        int id = Integer.parseInt(jTF_id.getText());
        String funcionario = jTF_func.getText();
        String titulo = String.valueOf(jCB_titulo.getSelectedItem());
        String genero = jTF_genero.getText();
        String studio = jTF_studio.getText();
        String cpf = String.valueOf(jCB_cpf.getSelectedItem());
        String data = dao.getData();
        String dataDevolv = dao.getDataDevolucao(data,Integer.valueOf(String.valueOf(jCB_periodo.getSelectedItem())));
        int periodo = Integer.valueOf(String.valueOf(jCB_periodo.getSelectedItem()));
        float valor = Float.valueOf(String.valueOf(jTF_valor.getText()));
        boolean devolvido = false;
        if(jCB_devolvido.isSelected())
            devolvido = true;
        else
            devolvido = false;
        
        locadora = new Locadora(id, funcionario, titulo, genero, studio, cpf, data, dataDevolv, periodo, valor, devolvido);
        return locadora;
    }
    
    public void FecharJanela() {
        dao.FechaConexao();
        this.dispose();
        JFrame jloca = new JanelaLocacoes();
        jloca.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JComboBox<String> jCB_cpf;
    private javax.swing.JCheckBox jCB_devolvido;
    private javax.swing.JComboBox<String> jCB_periodo;
    private javax.swing.JComboBox<String> jCB_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTF_func;
    private javax.swing.JTextField jTF_genero;
    private javax.swing.JTextField jTF_id;
    private javax.swing.JTextField jTF_studio;
    private javax.swing.JTextField jTF_valor;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    // End of variables declaration//GEN-END:variables

    private void formWindowClosing(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
